### ISSUE TITLE
Scripts not working in pack when using Technic Launcher

### ISSUE THREAD

**Issue by ChatFawkes** [INpureProjects/INpureCore#10]
I seem to have this weird bug related to the NEI culling scripts when using the Technic Launcher.

When I launch an instance of my pack via the Technic Launcher it will not activate the scripts and all the stuff that is supposed to be hidden still shows up in NEI.

Then I copied over all the configs, scripts, and mods exactly from that instance to a MultiMC instance and the NEI scripts work just fine (all the stuff is hidden).

InPureCore Version: 1.0.0B8-49

Link to my pack on [Technic](http://www.technicpack.net/modpack/fluxgalaxy.560255/about). (The problem happens when using the latest version of the pack: 0.7.16)

**Comment by denoflionsx** [comment]
Does the log say anything? The only thing I can think of is that the path
to the scripts is getting messed up somehow.

I may need to add some debug output to track this one down.

**Comment by ChatFawkes** [comment]
Alright I will give you log outputs from Technic and Multimc (give me a few moments).

**Comment by ChatFawkes** [comment]
[Technic debug log](https://gist.github.com/ChatFawkes/169705d7edb121611425)
[MultiMC debug log](https://gist.github.com/ChatFawkes/3d559885a6fd033e69ed)

**Comment by denoflionsx** [comment]
Ah. I see what is happening. Technic must be hijacking the FML log. I parse
the trace log to get registry names of everything.

I either need to figure out another way to get the data, or get in touch
with whoever makes that launcher to sort this problem out.

**Comment by ChatFawkes** [comment]
@CannibalVox is the Technic Launcher dev.

**Comment by CannibalVox** [comment]
Are we hijacking the FML log?  We put the FML output in the technic log, but I don't believe the vice versa is true.

**Comment by denoflionsx** [comment]
I don't know precisely what you guys do with the FML log, but whatever it is causes this method to not work properly:

https://github.com/INpureProjects/INpureCore/blob/master/src/main/java/info/inpureprojects/core/Preloader/FMLLogInterceptor.java#L56

Basically I grab the FML log and add a log4j filter to it. That filter passes the data from the logger back to a parser to figure out if that message is relevant to the GameRegistry or not. If so I parse it and store the result for later.

**Comment by denoflionsx** [comment]
@CannibalVox Again I don't know exactly how you guys are working with FML's logger, but if you're just redirecting it to another log4j logger you could give me a link to the class where that is being set up. I can silently poke around to see if Technic is on the classpath and add the filter on it too.

**Comment by CannibalVox** [comment]
Well we're not even redirecting it.  We're just extracting the stdout  from the launched process.   https://github.com/TechnicPack/LauncherCore/blob/master/src/main/java/net/technicpack/launchercore/launch/ProcessMonitorThread.java

If something I'm doing there isn't best practice, I'll be more than happy to change it.

**Comment by CannibalVox** [comment]
Is it possible that I'm launching it wrong and so it's doing something different from what you expect?

**Comment by denoflionsx** [comment]
I'm not sure. I work strictly within the log4j framework on the FML logger. I guess grabbing the stdout is causing the output to no longer go to the FML logger at all somehow.

I admit my knowledge of how those streams work under the hood is lacking, but I'm sure we can find a way to peacefully co-exist.

**Comment by CannibalVox** [comment]
Finally figured it out- modpack.jar was listed after Mojang's launchwrapper which has the same path for its log4j config file in-jar.  So the launchwrapper config was being used instead.  This is fixed in launcher beta 4.274 and is scheduled to go Stable a week from today.

**Comment by denoflionsx** [comment]
Nice catch. I'll be leaving the fix in place for future releases, but your
fix should get older versions working again.
