### ISSUE TITLE
ExU Drums, AE2 Cable Facades and TE Florbs not hiding

### ISSUE THREAD

**Issue by pennywis3** [INpureProjects/INpureCore#11]
I am using the latest versions of ExU and AE2 (rv2), and TE 4.0.0B8-23. As the title states drums, cable facades and florbs still show up although configured otherwise. Everything else works as advertised.

**Comment by denoflionsx** [comment]
Post your debug.log from INpureCore's configuration folder.

**Comment by pennywis3** [comment]
Further testing revealed that everything shows up that doesn't have a special handler, I just didn't want to hide it. NEI.hide and NEI.override don't seem to work.
[Here's the log](https://gist.github.com/pennywis3/46df0a47ac8ce442ae3e)

I'm also using the latest versions of NEI and INpureCore that are available.

**Comment by denoflionsx** [comment]
What launcher are you using?

**Comment by pennywis3** [comment]
I'm using the Technic launcher. I just noticed the other issue, *however*:
Results of downgrading INpureCore to 1.0.0B7-19:
* Vanilla: hidden
* Bibliocraft: hidden
* ExU: hidden
* TE: hidden
* FMP: hidden
* MFR: showing up (I think the unlocalized names changed in the alphas. That I can fix manually)
* AE2: showing up
* TCon: Tool Bindings and Scythe heads hidden, not sure what else should be.
* BC: broken, obviously

[New debug log for reference](https://gist.github.com/pennywis3/2ce141fd593c19063510)

**Comment by denoflionsx** [comment]
Interesting, since as far as I recall I haven't changed anything with the parser since like B6.

I'm looking into extracting the data directly from FML, so I'm not jumping into trying to fix the parser just yet. I'll probably leave the parser in place and just have it fall back to direct extraction should the resulting list end up empty.

**Comment by ChatFawkes** [comment]
What is the link to the maven repo, so I can grab the build for testing.

**Comment by denoflionsx** [comment]
http://files.inpureprojects.info/maven

**Comment by pennywis3** [comment]
[Insert redundant comment to confirm the fix works]
Well, that was quick. Thank you, good sir!
