### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xee1** [INpureProjects/INpureCore#12]
Hi @denoflionsx , I'm testing the latest version of INpureCore (INpureCore-[1.7.10]1.0.0B9-58) from maven, and this appear in console every startup:
http://pastebin.com/8fWrcs49

**Comment by denoflionsx** [comment]
Need the whole log. Can't see where the trace is leading. Thanks.

**Comment by Xee1** [comment]
Sure, just a second

**Comment by Xee1** [comment]
Here you are @denoflionsx :
https://www.dropbox.com/s/ca0hfc2fi2prxst/fml-client-latest.log?dl=0

**Comment by denoflionsx** [comment]
Looks like a break in the missing texture error filter. The error is
otherwise harmless. I'll look into it when I am back at my desk.

**Comment by Xee1** [comment]
Thanks for the help! Keep it up!

**Comment by Xee1** [comment]
Thanks !
