### ISSUE TITLE
Inpure Core+Other Logging Filter causes ClassCastException

### ISSUE THREAD

**Issue by ReikaKalseki** [INpureProjects/INpureCore#15]
Apparently, the log filtering functionality in InpureCore causes it to replace the entire logger with a custom class. This then interferes with other things working on the loggers - like my [LoggingFilter](https://github.com/ReikaKalseki/DragonAPI/blob/master/Auxiliary/LoggingFilters.java#L29)s - causing them to ClassCast when they try to load the loggers.

There are two ways to fix it. The easy way is to just make your logger extend Logger. This fixes the crash but will still break the other filterers. The *good* way is to change the filtering system a bit so that rather than replacing the logger you attach a filter. You can look at my LoggingFilter class to see how.

**Comment by denoflionsx** [comment]
Actually my logging filter uses a log4j filter, not a class replacement.
Really old versions used a replacement before I changed the entire thing.

**Comment by ReikaKalseki** [comment]
OK, so I will tell them to update.
