### ISSUE TITLE
Error with BuildCraft 6.3.2

### ISSUE THREAD

**Issue by mmelvin0** [INpureProjects/INpureCore#5]
As of BuildCraft 6.3.2, BCObject.getFacadesSize() fails because allFacades has changed from a LinkedList to an ArrayList. BCObject.obliterate_facades() will need the same treatment.

Here's the line in INpureCore:

https://github.com/INpureProjects/INpureCore/blob/b9c3ef8622bd48999511a3ba83ea13b772be9932/src/main/java/info/inpureprojects/core/NEI/gtfoMicroblocks/ScriptObjects/BCObject.java#L33

And here's the offending change in BuildCraft:

https://github.com/BuildCraft/BuildCraft/commit/5627c5dc7dffa3257fb82a90b673f382aae1da61#diff-5d60839fbb5eef3b55a7c15a7ad0a8b7L141

**Comment by denoflionsx** [comment]
Understood.

**Comment by mmelvin0** [comment]
Thanks for the very reasonable build system that I could understand after 4 beers. I made you a pull request that should hopefully fix the issue cleanly.

**Comment by denoflionsx** [comment]
Ha, I try to keep it simple. I prefer the 'invoke ant and forget' approach to building. Makes for a headacheless Jenkins setup.
