### ISSUE TITLE
[1.7.10]1.0.0B8-47 Typo in the path to the libs

### ISSUE THREAD

**Issue by bochen415** [INpureProjects/INpureCore#7]
http://paste.ubuntu.com/9908725/

line 2180+

http://files.inpureprojects.info/libscommons-codec-1.9.jar
vs
http://files.inpureprojects.info/libs/commons-codec-1.9.jar

**Comment by denoflionsx** [comment]
Ha. Go figure I make a freaking typo.

**Comment by bochen415** [comment]
Everybody does^^
