### ISSUE TITLE
Gendustry - No filtering correctly

### ISSUE THREAD

**Issue by LokiChaos** [INpureProjects/INpureCore#9]
It seems that Gendustry does something weird with Gene Samples and NEI.
My filtering script: Gendustry.js
```
if (FML.isModLoaded("gendustry")) {	
	NEI.hide("gendustry:GeneSample");
}
```
In debug.log
```Loading: User/Gendustry.js
hide called. Params: gendustry, GeneSample
Regex match found! gendustry:GeneSample matches gendustry:GeneSample.
Found ItemStack gendustry:GeneSample. 1xitem.gendustry.GeneSample@0```

However, when I bring up NEI it still shows all of the gene samples.  If I run `/INpureCore reload` once from within the game it hides them correctly.  I suspect that the filtering is being applied earlier than when Gendustry populates the samples.

**Comment by denoflionsx** [comment]
That is probably the case. More than likely it is injecting them via an
NEIConfig class which is also how the filter is applied. I guess the next
step is to inject via a delayed tick handler instead.

**Comment by denoflionsx** [comment]
You can try build 50 on maven to see if that commit sorts it out for you.

**Comment by LokiChaos** [comment]
Trying build 50...  It actually doesn't seem to apply /any/ filtering on login.  However, I run /INpureCore reload once and all filters correctly apply.  No errors, and debug.log seems to read as if all went correctly.  NotEnoughItems-1.7.10-1.0.4.83-universal and Forge 1291, should either of those be relevant

**Comment by denoflionsx** [comment]
Are you waiting a bit on login? It delays the filter load by 400 ticks on
build 50.

**Comment by LokiChaos** [comment]
Ok, waiting 90 seconds from loading the world and it works.  Thankyou!

**Comment by denoflionsx** [comment]
That seems excessive. It should only be 20 seconds max unless you are
seriously lagging. I may turn that delay down just in case.

**Comment by denoflionsx** [comment]
If you are still watching this ticket give 51 a try. I lowered the delay so you don't have to wait so long. I'm afraid if I leave it very long people will report it as a bug.

**Comment by LokiChaos** [comment]
Oh, I just waited 90 seconds to be absolutely sure it went through.  Just tried 51, I can still beat it, but it's quick enough unless you open inventory/NEI almost immediately it should get a chance to filter first.

**Comment by denoflionsx** [comment]
Alright. That works for me.
